//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunNet.PMNew.Web.OperateDocManagements {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperateDocManagements.OperateDocManagementSoap")]
    public interface OperateDocManagementSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 value 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDocManagement", ReplyAction="*")]
        SunNet.PMNew.Web.OperateDocManagements.AddDocManagementResponse AddDocManagement(SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetFileInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileInfo", ReplyAction="*")]
        SunNet.PMNew.Web.OperateDocManagements.GetFileInfoResponse GetFileInfo(SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocManagementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocManagement", Namespace="http://tempuri.org/", Order=0)]
        public SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequestBody Body;
        
        public AddDocManagementRequest() {
        }
        
        public AddDocManagementRequest(SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDocManagementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public AddDocManagementRequestBody() {
        }
        
        public AddDocManagementRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocManagementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocManagementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SunNet.PMNew.Web.OperateDocManagements.AddDocManagementResponseBody Body;
        
        public AddDocManagementResponse() {
        }
        
        public AddDocManagementResponse(SunNet.PMNew.Web.OperateDocManagements.AddDocManagementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDocManagementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddDocManagementResult;
        
        public AddDocManagementResponseBody() {
        }
        
        public AddDocManagementResponseBody(bool AddDocManagementResult) {
            this.AddDocManagementResult = AddDocManagementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileInfo", Namespace="http://tempuri.org/", Order=0)]
        public SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequestBody Body;
        
        public GetFileInfoRequest() {
        }
        
        public GetFileInfoRequest(SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetFileInfoRequestBody() {
        }
        
        public GetFileInfoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SunNet.PMNew.Web.OperateDocManagements.GetFileInfoResponseBody Body;
        
        public GetFileInfoResponse() {
        }
        
        public GetFileInfoResponse(SunNet.PMNew.Web.OperateDocManagements.GetFileInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileInfoResult;
        
        public GetFileInfoResponseBody() {
        }
        
        public GetFileInfoResponseBody(string GetFileInfoResult) {
            this.GetFileInfoResult = GetFileInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperateDocManagementSoapChannel : SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperateDocManagementSoapClient : System.ServiceModel.ClientBase<SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap>, SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap {
        
        public OperateDocManagementSoapClient() {
        }
        
        public OperateDocManagementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperateDocManagementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperateDocManagementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperateDocManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunNet.PMNew.Web.OperateDocManagements.AddDocManagementResponse SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap.AddDocManagement(SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequest request) {
            return base.Channel.AddDocManagement(request);
        }
        
        public bool AddDocManagement(string value) {
            SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequest inValue = new SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequest();
            inValue.Body = new SunNet.PMNew.Web.OperateDocManagements.AddDocManagementRequestBody();
            inValue.Body.value = value;
            SunNet.PMNew.Web.OperateDocManagements.AddDocManagementResponse retVal = ((SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap)(this)).AddDocManagement(inValue);
            return retVal.Body.AddDocManagementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunNet.PMNew.Web.OperateDocManagements.GetFileInfoResponse SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap.GetFileInfo(SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequest request) {
            return base.Channel.GetFileInfo(request);
        }
        
        public string GetFileInfo(int id) {
            SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequest inValue = new SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequest();
            inValue.Body = new SunNet.PMNew.Web.OperateDocManagements.GetFileInfoRequestBody();
            inValue.Body.id = id;
            SunNet.PMNew.Web.OperateDocManagements.GetFileInfoResponse retVal = ((SunNet.PMNew.Web.OperateDocManagements.OperateDocManagementSoap)(this)).GetFileInfo(inValue);
            return retVal.Body.GetFileInfoResult;
        }
    }
}
