//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunNet.PMNew.WinLogin.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-01-01")]
        public global::System.DateTime CheckUpdateDate
        {
            get
            {
                return ((global::System.DateTime)(this["CheckUpdateDate"]));
            }
            set
            {
                this["CheckUpdateDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ISCheckUpdate
        {
            get
            {
                return ((bool)(this["ISCheckUpdate"]));
            }
            set
            {
                this["ISCheckUpdate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float LocalVersion
        {
            get
            {
                return ((float)(this["LocalVersion"]));
            }
            set
            {
                this["LocalVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sorry to tell you the application get an error, we\'ll appreciate if you send the " +
            "error informations to us, our email: project@sunnet.us. The error messages:\r\n{0}" +
            "\r\n-----------Sunnet(www.sunnet.us) ")]
        public string ErrorFormat
        {
            get
            {
                return ((string)(this["ErrorFormat"]));
            }
            set
            {
                this["ErrorFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowScriptErrors
        {
            get
            {
                return ((bool)(this["ShowScriptErrors"]));
            }
            set
            {
                this["ShowScriptErrors"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Low")]
        public global::SunNet.PMNew.WinLogin.PopupBlockerFilterLevel FilterLevel
        {
            get
            {
                return ((global::SunNet.PMNew.WinLogin.PopupBlockerFilterLevel)(this["FilterLevel"]));
            }
            set
            {
                this["FilterLevel"] = value;
            }
        }
    }
}
