//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunNet.PMNew.WinLogin.PMLogin1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pm.sunnet.us/", ConfigurationName="PMLogin1.PMLoginSoap")]
    public interface PMLoginSoap {
        
        // CODEGEN: 命名空间 http://pm.sunnet.us/ 的元素名称 desUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pm.sunnet.us/Login", ReplyAction="*")]
        SunNet.PMNew.WinLogin.PMLogin1.LoginResponse Login(SunNet.PMNew.WinLogin.PMLogin1.LoginRequest request);
        
        // CODEGEN: 命名空间 http://pm.sunnet.us/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pm.sunnet.us/GetVersion", ReplyAction="*")]
        SunNet.PMNew.WinLogin.PMLogin1.GetVersionResponse GetVersion(SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequest request);
        
        // CODEGEN: 命名空间 http://pm.sunnet.us/ 的元素名称 file 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pm.sunnet.us/Update", ReplyAction="*")]
        SunNet.PMNew.WinLogin.PMLogin1.UpdateResponse Update(SunNet.PMNew.WinLogin.PMLogin1.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(SunNet.PMNew.WinLogin.PMLogin1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string desUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string desPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool rememberMe;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string desUserName, string desPassword, bool rememberMe) {
            this.desUserName = desUserName;
            this.desPassword = desPassword;
            this.rememberMe = rememberMe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(SunNet.PMNew.WinLogin.PMLogin1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult, string id) {
            this.LoginResult = LoginResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class GetVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetVersionRequestBody() {
        }
        
        public GetVersionRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(SunNet.PMNew.WinLogin.PMLogin1.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SunNet.PMNew.WinLogin.PMLogin1.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://pm.sunnet.us/", Order=0)]
        public SunNet.PMNew.WinLogin.PMLogin1.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SunNet.PMNew.WinLogin.PMLogin1.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pm.sunnet.us/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PMLoginSoapChannel : SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMLoginSoapClient : System.ServiceModel.ClientBase<SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap>, SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap {
        
        public PMLoginSoapClient() {
        }
        
        public PMLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunNet.PMNew.WinLogin.PMLogin1.LoginResponse SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap.Login(SunNet.PMNew.WinLogin.PMLogin1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string desUserName, string desPassword, bool rememberMe, out string id) {
            SunNet.PMNew.WinLogin.PMLogin1.LoginRequest inValue = new SunNet.PMNew.WinLogin.PMLogin1.LoginRequest();
            inValue.Body = new SunNet.PMNew.WinLogin.PMLogin1.LoginRequestBody();
            inValue.Body.desUserName = desUserName;
            inValue.Body.desPassword = desPassword;
            inValue.Body.rememberMe = rememberMe;
            SunNet.PMNew.WinLogin.PMLogin1.LoginResponse retVal = ((SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap)(this)).Login(inValue);
            id = retVal.Body.id;
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunNet.PMNew.WinLogin.PMLogin1.GetVersionResponse SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap.GetVersion(SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion(string key) {
            SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequest inValue = new SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequest();
            inValue.Body = new SunNet.PMNew.WinLogin.PMLogin1.GetVersionRequestBody();
            inValue.Body.key = key;
            SunNet.PMNew.WinLogin.PMLogin1.GetVersionResponse retVal = ((SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunNet.PMNew.WinLogin.PMLogin1.UpdateResponse SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap.Update(SunNet.PMNew.WinLogin.PMLogin1.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string file) {
            SunNet.PMNew.WinLogin.PMLogin1.UpdateRequest inValue = new SunNet.PMNew.WinLogin.PMLogin1.UpdateRequest();
            inValue.Body = new SunNet.PMNew.WinLogin.PMLogin1.UpdateRequestBody();
            inValue.Body.file = file;
            SunNet.PMNew.WinLogin.PMLogin1.UpdateResponse retVal = ((SunNet.PMNew.WinLogin.PMLogin1.PMLoginSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
    }
}
